name: Deploy to MiniKube using GitHub Actions CI/CD

on:
  push:
    branches: [ main ]
# on:
#   workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build Node js dockerImage and deploy in MiniKube

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: List repo files
      run: ls -l


    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/minikubenode-app:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Start Minikube
      uses: medyagh/setup-minikube@latest

    - name: Verify Minikube cluster
      run: kubectl get pods -A

    - name: Deploy to Kubernetes
      run: kubectl apply -f deployk8s_minicube.yml


    # This will block until the pods are ready — or show why they’re not.
    - name: Wait for Deployment to be ready
      run: kubectl rollout status deployment/nodejs-mini-deployment

    - name: Debug Kubernetes state
      run: |
        kubectl get all
        kubectl describe deployment nodejs-mini-deployment
        kubectl get endpoints nodejs-app-service


# just

    - name: Test service URLs
      run: |
        minikube service list
        minikube service nodejs-app-service --url
